Controllers/AdminController.cs
using Boolflix.Models.DataHome;
using Boolflix.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Boolflix.Data;
using Boolflix.Models.Repository;
using Azure;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.Hosting;
using Microsoft.Build.Framework;

namespace Boolflix.Controllers
{   
    [Authorize]
    [Route("[controller]/[action]/{id?}", Order = 0)]
    public class AdminController : Controller
    {

        public BoolflixDbContext db;
        IdbContentRepository boolflixRepository;

        public AdminController(IdbContentRepository _boolflixRepository, BoolflixDbContext _db) : base()
        {
            db = _db;
            boolflixRepository = _boolflixRepository;
        }

        public IActionResult CreateFilm()
        {
            FormData formData = new FormData();

            formData.Film = new Film();
            formData.Genres = new List<SelectListItem>();
            formData.Casts = new List<SelectListItem>();

            List<Cast> castList = db.Casts.ToList();

            foreach (Cast cast in castList)
            {
                formData.Casts.Add(new SelectListItem(cast.Nome + " " + cast.Lastnome,cast.Id.ToString()));
            }

            List<Genre> genresList = db.Genres.ToList();

            foreach (Genre genre in genresList)
            {
                formData.Genres.Add(new SelectListItem(genre.Name, genre.Id.ToString()));
            }

            return View(formData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateFilm(FormData formData)
        {
            formData.Film.Remaining_time = formData.Film.Duration;
            if (!ModelState.IsValid)
            {             
                formData.Genres = new List<SelectListItem>();
                List<Genre> genresList = db.Genres.ToList();
                foreach (Genre genre in genresList)
                {
                    formData.Genres.Add(new SelectListItem(genre.Name, genre.Id.ToString()));
                }

                formData.Casts = new List<SelectListItem>();
                List<Cast> castList = db.Casts.ToList();
                foreach (Cast cast in castList)
                {
                    formData.Casts.Add(new SelectListItem(cast.Nome + " " + cast.Lastnome, cast.Id.ToString()));
                }

                return View(formData);
            }
            
            boolflixRepository.CreateFilm(formData.Film, formData.SelectedGenres, formData.SelectedCasts);
            
            return RedirectToAction("Index","Home");
        }

        public IActionResult CreateSerie()
        {
            FormData formData = new FormData();

            formData.Serie = new SerieTV();
            formData.Genres = new List<SelectListItem>();
            formData.Casts = new List<SelectListItem>();

            List<Cast> castList = db.Casts.ToList();

            foreach (Cast cast in castList)
            {
                formData.Casts.Add(new SelectListItem(cast.Nome + " " + cast.Lastnome, cast.Id.ToString()));
            }

            List<Genre> genresList = db.Genres.ToList();

            foreach (Genre genre in genresList)
            {
                formData.Genres.Add(new SelectListItem(genre.Name, genre.Id.ToString()));
            }

            return View(formData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSerie(FormData formData)
        {
            if (!ModelState.IsValid)
            {
                formData.Genres = new List<SelectListItem>();
                List<Genre> genresList = db.Genres.ToList();
                foreach (Genre genre in genresList)
                {
                    formData.Genres.Add(new SelectListItem(genre.Name, genre.Id.ToString()));
                }

                formData.Casts = new List<SelectListItem>();
                List<Cast> castList = db.Casts.ToList();
                foreach (Cast cast in castList)
                {
                    formData.Casts.Add(new SelectListItem(cast.Nome + " " + cast.Lastnome, cast.Id.ToString()));
                }

                return View(formData);
            }

            boolflixRepository.CreateSerie(formData.Serie, formData.SelectedGenres, formData.SelectedCasts);

            return RedirectToAction("Index","Home");
        }

        public IActionResult UpdateFilm(int id)
        {

            Film film = boolflixRepository.GetFilmById(id);

            if (film == null)
                return NotFound();

            FormData formData = new FormData();

            formData.Film = film;
            formData.Genres = new List<SelectListItem>();
            formData.Casts = new List<SelectListItem>();

            List<Cast> castList = db.Casts.ToList();

            foreach (Cast cast in castList)
            {
                formData.Casts.Add(new SelectListItem(cast.Nome + " " + cast.Lastnome, cast.Id.ToString(), film.Casts.Any(t => t.Id == cast.Id)));
            }

            List<Genre> genresList = db.Genres.ToList();

            foreach (Genre genre in genresList)
            {
                formData.Genres.Add(new SelectListItem(genre.Name, genre.Id.ToString(),film.Genres.Any(t => t.Id == genre.Id)));
            }

            return View(formData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateFilm(int id, FormData formData)
        {

            if (!ModelState.IsValid)
            {
                formData.Film.Id = id;
                //return View(postItem);
                formData.Genres = new List<SelectListItem>();
                List<Genre> genresList = db.Genres.ToList();
                foreach (Genre genre in genresList)
                {
                    formData.Genres.Add(new SelectListItem(genre.Name, genre.Id.ToString()));
                }

                formData.Casts = new List<SelectListItem>();
                List<Cast> castList = db.Casts.ToList();
                foreach (Cast cast in castList)
                {
                    formData.Casts.Add(new SelectListItem(cast.Nome + " " + cast.Lastnome, cast.Id.ToString()));
                }

                return View(formData);
            }

            //update esplicito con nuovo oggetto
            Film filmItem = boolflixRepository.GetFilmById(id);

            if (filmItem == null)
            {
                return NotFound();
            }

            boolflixRepository.UpdateFilm(filmItem, formData.Film,formData.SelectedGenres,formData.SelectedCasts);

            return RedirectToAction("Index","Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteFilm(int id)
        {
            Film filmTodelete = boolflixRepository.GetFilmById(id);

            if (filmTodelete == null)
            {
                return NotFound();
            }

            boolflixRepository.DeleteFilm(filmTodelete);


            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteSerie(int id)
        {
            SerieTV serieTodelete = boolflixRepository.GetSerieById(id);

            if (serieTodelete == null)
            {
                return NotFound();
            }

            foreach(Season seasons in serieTodelete.Seasons)
            {
                if(seasons.Episodes != null)
                {
                    seasons.Episodes.Clear();
                }

                db.SaveChanges();
            }

            boolflixRepository.DeleteSerie(serieTodelete);


            return RedirectToAction("Index", "Home");
        }

        public IActionResult CreateSeason(int id)
        {
            SerieTV serieTV = boolflixRepository.GetSerieById(id);
            
            Season season = new Season();
            season.SeasonNumber = serieTV.Seasons.Count() + 1;
            season.SerieTV = serieTV;
            season.SerieTVId = id;
            
            db.Seasons.Add(season);
            db.SaveChanges();

            return RedirectToAction("DetailSerie", "Home", new { ID = id });
        }
    }
}

Controllers/EpisodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Boolflix.Data;
using Boolflix.Models;

namespace Boolflix.Controllers
{
    public class EpisodesController : Controller
    {
        private readonly BoolflixDbContext _context;

        public EpisodesController(BoolflixDbContext context)
        {
            _context = context;
        }

        // GET: Episodes
        public async Task<IActionResult> Index()
        {
            var boolflixDbContext = _context.Episodes.Include(e => e.Seasons);
            return View(await boolflixDbContext.ToListAsync());
        }

        // GET: Episodes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Episodes == null)
            {
                return NotFound();
            }

            var episode = await _context.Episodes
                .Include(e => e.Seasons)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (episode == null)
            {
                return NotFound();
            }

            return View(episode);
        }

        // GET: Episodes/Create
        public IActionResult Create()
        {
            ViewData["SeasonId"] = new SelectList(_context.Seasons, "Id", "Id");
            return View();
        }

        // POST: Episodes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Duration,Remaining_time,SeasonId")] Episode episode)
        {
            if (ModelState.IsValid)
            {
                _context.Add(episode);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SeasonId"] = new SelectList(_context.Seasons, "Id", "Id", episode.SeasonId);
            return View(episode);
        }

        // GET: Episodes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Episodes == null)
            {
                return NotFound();
            }

            var episode = await _context.Episodes.FindAsync(id);
            if (episode == null)
            {
                return NotFound();
            }
            ViewData["SeasonId"] = new SelectList(_context.Seasons, "Id", "Id", episode.SeasonId);
            return View(episode);
        }

        // POST: Episodes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Duration,Remaining_time,SeasonId")] Episode episode)
        {
            if (id != episode.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(episode);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EpisodeExists(episode.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SeasonId"] = new SelectList(_context.Seasons, "Id", "Id", episode.SeasonId);
            return View(episode);
        }

        // GET: Episodes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Episodes == null)
            {
                return NotFound();
            }

            var episode = await _context.Episodes
                .Include(e => e.Seasons)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (episode == null)
            {
                return NotFound();
            }

            return View(episode);
        }

        // POST: Episodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Episodes == null)
            {
                return Problem("Entity set 'BoolflixDbContext.Episodes'  is null.");
            }
            var episode = await _context.Episodes.FindAsync(id);
            if (episode != null)
            {
                _context.Episodes.Remove(episode);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EpisodeExists(int id)
        {
          return _context.Episodes.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using Boolflix.Data;
using Boolflix.Models;
using Boolflix.Models.DataHome;
using Boolflix.Models.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Boolflix.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public BoolflixDbContext db;
        IdbContentRepository boolflixRepository;

        public HomeController(ILogger<HomeController> logger, IdbContentRepository _boolflixRepository, BoolflixDbContext _db) : base()
        {
            _logger = logger;

            db = _db;
            boolflixRepository = _boolflixRepository;
        }

        public IActionResult Index()
        {
            IndexData2 indexData2 = new IndexData2();
            indexData2.IndexDataAzione = boolflixRepository.SearchByGenre("Azione");
            indexData2.IndexDataAvventura = boolflixRepository.SearchByGenre("Avventura");
            indexData2.IndexDataHorror = boolflixRepository.SearchByGenre("Horror");
            indexData2.IndexDataFantasy = boolflixRepository.SearchByGenre("Fantasy");
            
            return View(indexData2);
        }

        public IActionResult DetailFilm(int id)
        {
            Film film = boolflixRepository.GetFilmById(id);
            return View(film);
        }
        public IActionResult DetailSerie(int id)
        {
            SerieTV serieTV = boolflixRepository.GetSerieById(id);

            return View(serieTV);
        }

        public IActionResult IndexFilm(int id)
        {
            List<Film> films = boolflixRepository.AllFilm();
            return View(films);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/DetailFilm.cshtml
@model Film

<div class="container overflow-hidden">
    <div class="row">
        <div class="col">
            <img src="@Model.Poster" alt="@Model.Title" style="width:600px;height:890px;" />
        </div>
        <div class="col">
            <div class="p-3 border bg-light"><div><strong>Titolo: </strong>@Model.Title</div></div>
            <div class="p-3 border bg-light"><div><strong>Durata: </strong>@Model.Duration min</div></div>
            <div class="p-3 border bg-light"><div><strong>Descrizione: </strong>@Model.Description</div></div>
            <div class="p-3 border bg-light"><div><strong>PG: </strong>@Model.PG anni</div></div>
            <div class="p-3 border bg-light">
                <div>
                    <strong>Attori: </strong>@foreach (Cast cast in Model.Casts)
                    {
                        <span>@cast.Nome</span>
                        <span>@cast.Lastnome,</span>
                    }
                </div>
            </div>
            <div class="p-3 border bg-light"><div><strong>Anno: </strong>@Model.Year.Year</div></div>
        </div>
    </div>
</div>

Views/Home/DetailSerie.cshtml
@model SerieTV

<div class="container overflow-hidden">
    <div class="row">
        <div class="col">
            <img src="@Model.Poster" alt="@Model.Title" style="width:600px;height:890px;"/>
        </div>
        <div class="col">
            <div class="p-3 border bg-light"><div><strong>Titolo: </strong>@Model.Title</div></div>
            <div class="p-3 border bg-light"><div><strong>N° Stagioni: </strong>@Model.Seasons.Count()</div></div>
            <div class="p-3 border bg-light"><div><strong>Descrizione: </strong>@Model.Description</div></div>
            <div class="p-3 border bg-light"><div><strong>PG: </strong>@Model.PG</div></div>
            <div class="p-3 border bg-light">
                <div>
                <strong>Attori: </strong>@foreach(Cast cast in Model.Casts){
                        <span>@cast.Nome</span>
                        <span>@cast.Lastnome</span>
                    }
                </div>
            </div>
            <div class="p-3 border bg-light"><div><strong>Anno: </strong>@Model.Year.Year</div></div>
            <div class="p-3 border bg-light">
                <div>
                    @foreach (Season season in Model.Seasons)
                    {
                        <span><strong>Stagione: </strong> @season.SeasonNumber</span>
                        @if (season.Episodes != null)
                        {
                            @foreach (Episode episode in season.Episodes){
                                <div class="p-3 border bg-light"><div><strong>Episodio N°: </strong>@episode.Id</div></div>
                                <div class="p-3 border bg-light"><div><strong>Titolo: </strong>@episode.Title</div></div>
                                <div class="p-3 border bg-light"><div><strong>Descriozione: </strong>@episode.Description</div></div>
                                <div class="p-3 border bg-light"><div><strong>Durata: </strong>@episode.Duration</div></div>
                            }
                        }

                    }
                </div>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="d-flex justify-content-between mt-2">
                    <a class="btn mr-2" href="@Url.Action("CreateSeason", "Admin", new { id = Model.Id })">
                        <div class="col-md-4">
                            <div class="card" style="width: 18rem;">
                                <img src="https://cdn.pixabay.com/photo/2017/11/10/05/24/add-2935429_960_720.png" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">Aggiungi una stagione</h5>
                                </div>
                            </div>
                        </div>
                    </a>
                    <a class="btn mr-2" href="@Url.Action("Create", "Episodes")">
                        <div class="col-md-4">
                            <div class="card" style="width: 18rem;">
                                <img src="https://cdn.pixabay.com/photo/2017/11/10/05/24/add-2935429_960_720.png" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">Aggiungi un episodio</h5>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@using Boolflix.Models.DataHome
@{
    ViewData["Title"] = "Home Page";
}
@model IndexData2
@if (Model.IndexDataAzione.Films.Count > 0 || Model.IndexDataAzione.Series.Count > 0)
{
    <h1>Azione</h1>
    <div class="container-fluid">
        <div class="row index_boolflix">
        
            @foreach (Film film in Model.IndexDataAzione.Films)
            {
                <div class="col-md-4">
                    <div class="card">
                        <a class="btn mr-2" href="@Url.Action("DetailFilm", "Home", new { id = film.Id })"><img src="@film.Poster" class="card-img-top" alt="@film.Title"></a>
                        <div class="card-body">
                            <h5 class="card-title">@film.Title</h5>
                            <h6 class="card-subtitle mb-2" style="color: green;">@film.Compatibility% Compatibile</h6>
                            <p class="card-text">@film.Description</p>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="btn mr-2" href="@Url.Action("UpdateFilm", "Admin", new { id = film.Id })">Modifica</a>
                                <form asp-controller="Admin" asp-action="DeleteFilm" asp-route-id="@film.Id" method="post" class="d-inline btn">
                                    <button type="submit">
                                        Elimina
                                    </button>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            }
        
        
            @foreach (SerieTV serie in Model.IndexDataAzione.Series)
            {
                <div class="col-md-4">
                    <div class="card">
                        <a class="btn mr-2" href="@Url.Action("DetailSerie", "Home", new { id = serie.Id })"><img src="@serie.Poster" class="card-img-top" alt="@serie.Title"></a>
                        <div class="card-body">
                            <h5 class="card-title">@serie.Title</h5>
                            <h6 class="card-subtitle mb-2" style="color: green;">@serie.Compatibility% Compatibile</h6>
                            <p class="card-text">@serie.Description</p>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <form asp-controller="Admin" asp-action="DeleteSerie" asp-route-id="@serie.Id" method="post" class="d-inline btn">
                                    <button type="submit">
                                        Elimina
                                    </button>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}

@if (Model.IndexDataAvventura.Films.Count > 0 || Model.IndexDataAvventura.Series.Count > 0)
{
    <h1>Avventura</h1>
    <div class="container-fluid">
        <div class="row index_boolflix">

            @foreach (Film film in Model.IndexDataAvventura.Films)
            {
                <div class="col-md-4">
                    <div class="card">
                        <a class="btn mr-2" href="@Url.Action("DetailFilm", "Home", new { id = film.Id })"><img src="@film.Poster" class="card-img-top" alt="@film.Title"></a>
                        <div class="card-body">
                            <h5 class="card-title">@film.Title</h5>
                            <h6 class="card-subtitle mb-2" style="color: green;">@film.Compatibility% Compatibile</h6>
                            <p class="card-text">@film.Description</p>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="btn mr-2" href="@Url.Action("UpdateFilm", "Admin", new { id = film.Id })">Modifica</a>
                                <form asp-controller="Admin" asp-action="DeleteFilm" asp-route-id="@film.Id" method="post" class="d-inline btn">
                                    <button type="submit">
                                        Elimina
                                    </button>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            }


            @foreach (SerieTV serie in Model.IndexDataAvventura.Series)
            {
                <div class="col-md-4">
                    <div class="card">
                        <a class="btn mr-2" href="@Url.Action("DetailSerie", "Home", new { id = serie.Id })"><img src="@serie.Poster" class="card-img-top" alt="@serie.Title"></a>
                        <div class="card-body">
                            <h5 class="card-title">@serie.Title</h5>
                            <h6 class="card-subtitle mb-2" style="color: green;">@serie.Compatibility% Compatibile</h6>
                            <p class="card-text">@serie.Description</p>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <form asp-controller="Admin" asp-action="DeleteSerie" asp-route-id="@serie.Id" method="post" class="d-inline btn">
                                    <button type="submit">
                                        Elimina
                                    </button>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}

@if (Model.IndexDataHorror.Films.Count > 0 || Model.IndexDataHorror.Series.Count > 0)
{
    <h1>Horror</h1>
    <div class="container-fluid">
        <div class="row index_boolflix">

            @foreach (Film film in Model.IndexDataHorror.Films)
            {
                <div class="col-md-4">
                    <div class="card">
                        <a class="btn mr-2" href="@Url.Action("DetailFilm", "Home", new { id = film.Id })"><img src="@film.Poster" class="card-img-top" alt="@film.Title"></a>
                        <div class="card-body">
                            <h5 class="card-title">@film.Title</h5>
                            <h6 class="card-subtitle mb-2" style="color: green;">@film.Compatibility% Compatibile</h6>
                            <p class="card-text">@film.Description</p>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="btn mr-2" href="@Url.Action("UpdateFilm", "Admin", new { id = film.Id })">Modifica</a>
                                <form asp-controller="Admin" asp-action="DeleteFilm" asp-route-id="@film.Id" method="post" class="d-inline btn">
                                    <button type="submit">
                                        Elimina
                                    </button>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            }


            @foreach (SerieTV serie in Model.IndexDataHorror.Series)
            {
                <div class="col-md-4">
                    <div class="card">
                        <a class="btn mr-2" href="@Url.Action("DetailSerie", "Home", new { id = serie.Id })"><img src="@serie.Poster" class="card-img-top" alt="@serie.Title"></a>
                        <div class="card-body">
                            <h5 class="card-title">@serie.Title</h5>
                            <h6 class="card-subtitle mb-2" style="color: green;">@serie.Compatibility% Compatibile</h6>
                            <p class="card-text">@serie.Description</p>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <form asp-controller="Admin" asp-action="DeleteSerie" asp-route-id="@serie.Id" method="post" class="d-inline btn">
                                    <button type="submit">
                                        Elimina
                                    </button>
                                </form>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}

@if(User.Identity.IsAuthenticated)
{
    <div class="d-flex">
        <a class="nav-link text-dark d-inline" asp-area="" asp-controller="Admin" asp-action="CreateFilm">
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img src="https://cdn.pixabay.com/photo/2017/11/10/05/24/add-2935429_960_720.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Aggiungi un Film</h5>
                    </div>
                </div>
            </div>
        </a>
        <a class="nav-link text-dark d-inline" asp-area="" asp-controller="Admin" asp-action="CreateSerie">
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img src="https://cdn.pixabay.com/photo/2017/11/10/05/24/add-2935429_960_720.png" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Aggiungi una Serie</h5>
                    </div>
                </div>
            </div>
        </a>
    </div>
}

Views/Home/IndexFilm.cshtml
@model List<Film>
<h2>Lista dei film</h2>
<div class="container-fluid">
    <div class="row index_boolflix">
        @foreach (Film film in Model)
        {
            <div class="col-md-4">
                <div class="card">
                    <a class="btn mr-2" href="@Url.Action("DetailFilm", "Home", new { id = film.Id })"><img src="@film.Poster" class="card-img-top" alt="@film.Title"></a>
                    <div class="card-body">
                        <h5 class="card-title">@film.Title</h5>
                        <h6 class="card-subtitle mb-2" style="color: green;">@film.Compatibility% Compatibile</h6>
                        <p class="card-text">@film.Description</p>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="btn mr-2" href="@Url.Action("UpdateFilm", "Admin", new { id = film.Id })">Modifica</a>
                            <form asp-controller="Admin" asp-action="DeleteFilm" asp-route-id="@film.Id" method="post" class="d-inline btn">
                                <button type="submit">
                                    Elimina
                                </button>
                            </form>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>